version: '3.8'
services:
  biance-alpha-address-monitor:
    build: 
      context: .
      args:
        - HTTP_PROXY=
        - HTTPS_PROXY=
    container_name: biance-alpha-address-monitor
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - TZ=Asia/Shanghai
      - ENV=dev  # 改为开发环境
      - IS_DOCKER=true
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890

      # Twitter API配置
      - TWITTER_API_BASE_URL=http://host.docker.internal:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    shm_size: '0.5gb'
    restart: "no" 